### ISSUE TITLE
能否增加linux-mipsle架构？

### ISSUE THREAD

**Issue by zjw345** [GenshinMinecraft/nezha-agent-rs#1]
能否在工作流增加编译linux-mipsle架构？自己增加报错失败了

**Comment by GenshinMinecraft** [comment]
实际上，已经不止一个人来问过我关于 Mips 架构的问题了

但是 Mips 架构在 Rust 官方支持是放在 Tier3 的，这会导致编译非常麻烦且稳定性无法保证

所以不好意思，如果你有需要，可以自行下载仓库编译，你也许需要一同编译 Std 标准库

不好意思

**Comment by zjw345** [comment]
我试着编译，总数提示error: component 'rust-std' for target 'mipsel-unknown-linux-musl' is unavailable for download for channel 'stable'。解决不了。原因貌似是mipsel-unknown-linux-musl 不支持rust-std组件。
从这看到不支持rust-std：
https://rust-lang.github.io/rustup-components-history/mipsel-unknown-linux-gnu.html

**Comment by zjw345** [comment]
真的没办法吗？

**Comment by GenshinMinecraft** [comment]
> 真的没办法吗？

自行编译可能是个不错的选择，不在 T1 里面的我是没试过的

还有编译到 'mipsel-unknown-linux-musl' 需要 nightly
