### ISSUE TITLE
是否能添加tls模式支持？

### ISSUE THREAD

**Issue by mustang0394** [GenshinMinecraft/nezha-agent-rs#2]
是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式
谢谢~

**Comment by GenshinMinecraft** [comment]
好，等会我看看

**Comment by GenshinMinecraft** [comment]
> 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~

劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签

**Comment by mustang0394** [comment]
> > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> 
> 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签

默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查
![图片](https://github.com/user-attachments/assets/486c58f8-c041-471c-949b-c111b20e99f4)

**Comment by GenshinMinecraft** [comment]
> > > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> > 
> > 
> > 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签
> 
> 默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查 ![图片](https://private-user-images.githubusercontent.com/128272411/365410431-486c58f8-c041-471c-949b-c111b20e99f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjMyMzYsIm5iZiI6MTcyNTc2MjkzNiwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEwNDMxLTQ4NmM1OGY4LWMwNDEtNDcxYy05NDliLWMxMTFiMjBlOTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjZiZWQyMDk1OWRjYmIyNjdjMTdiYTAwYWE2MmUzNjc1ODhiOWQwNzRmZjE3NWFjOTU0ZDIzMTdiYmY3Y2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h1L0JSh6rQ2gr0KVHOhP-eEg1hOOu66-6rJKfmpA70A)

好的，其实官方很多东西我都没写，最后就加个tls吧

**Comment by mustang0394** [comment]
> > > > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> > > 
> > > 
> > > 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签
> > 
> > 
> > 默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查 ![图片](https://private-user-images.githubusercontent.com/128272411/365410431-486c58f8-c041-471c-949b-c111b20e99f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjMyMzYsIm5iZiI6MTcyNTc2MjkzNiwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEwNDMxLTQ4NmM1OGY4LWMwNDEtNDcxYy05NDliLWMxMTFiMjBlOTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjZiZWQyMDk1OWRjYmIyNjdjMTdiYTAwYWE2MmUzNjc1ODhiOWQwNzRmZjE3NWFjOTU0ZDIzMTdiYmY3Y2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h1L0JSh6rQ2gr0KVHOhP-eEg1hOOu66-6rJKfmpA70A)
> 
> 好的，其实官方很多东西我都没写，最后就加个tls吧

感谢

**Comment by GenshinMinecraft** [comment]
> > > > > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> > > > 
> > > > 
> > > > 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签
> > > 
> > > 
> > > 默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查 ![图片](https://private-user-images.githubusercontent.com/128272411/365410431-486c58f8-c041-471c-949b-c111b20e99f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjMyMzYsIm5iZiI6MTcyNTc2MjkzNiwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEwNDMxLTQ4NmM1OGY4LWMwNDEtNDcxYy05NDliLWMxMTFiMjBlOTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjZiZWQyMDk1OWRjYmIyNjdjMTdiYTAwYWE2MmUzNjc1ODhiOWQwNzRmZjE3NWFjOTU0ZDIzMTdiYmY3Y2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h1L0JSh6rQ2gr0KVHOhP-eEg1hOOu66-6rJKfmpA70A)
> > 
> > 
> > 好的，其实官方很多东西我都没写，最后就加个tls吧
> 
> 感谢

我 Push 了个新版本，但是我没有 TLS 环境测试，要不你试试用下？
https://github.com/GenshinMinecraft/nezha-agent-rs/actions/runs/10756674232

**Comment by mustang0394** [comment]
> > > > > > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> > > > > 
> > > > > 
> > > > > 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签
> > > > 
> > > > 
> > > > 默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查 ![图片](https://private-user-images.githubusercontent.com/128272411/365410431-486c58f8-c041-471c-949b-c111b20e99f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjMyMzYsIm5iZiI6MTcyNTc2MjkzNiwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEwNDMxLTQ4NmM1OGY4LWMwNDEtNDcxYy05NDliLWMxMTFiMjBlOTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjZiZWQyMDk1OWRjYmIyNjdjMTdiYTAwYWE2MmUzNjc1ODhiOWQwNzRmZjE3NWFjOTU0ZDIzMTdiYmY3Y2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h1L0JSh6rQ2gr0KVHOhP-eEg1hOOu66-6rJKfmpA70A)
> > > 
> > > 
> > > 好的，其实官方很多东西我都没写，最后就加个tls吧
> > 
> > 
> > 感谢
> 
> 我 Push 了个新版本，但是我没有 TLS 环境测试，要不你试试用下？ https://github.com/GenshinMinecraft/nezha-agent-rs/actions/runs/10756674232

测了一下，可以正常使用了，感谢

不过这个内存的读数是不是有问题？是把buff/cache也算在使用内存中了吗？
![图片](https://github.com/user-attachments/assets/34ca16e3-3b4a-488e-896f-5c557f7b0b21)

**Comment by GenshinMinecraft** [comment]
> > > > > > > 是否能支持HTTP2的gRPC数据回报功能？也就是官方客户端的`--tls`模式 谢谢~
> > > > > > 
> > > > > > 
> > > > > > 劳烦问一下，官方客户端 tls 是鉴定由正规 CA 颁发的吗，还是说接受自签
> > > > > 
> > > > > 
> > > > > 默认是不支持自签的，有另外一个参数 `--insecure` 忽略证书检查 ![图片](https://private-user-images.githubusercontent.com/128272411/365410431-486c58f8-c041-471c-949b-c111b20e99f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjMyMzYsIm5iZiI6MTcyNTc2MjkzNiwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEwNDMxLTQ4NmM1OGY4LWMwNDEtNDcxYy05NDliLWMxMTFiMjBlOTlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjZiZWQyMDk1OWRjYmIyNjdjMTdiYTAwYWE2MmUzNjc1ODhiOWQwNzRmZjE3NWFjOTU0ZDIzMTdiYmY3Y2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h1L0JSh6rQ2gr0KVHOhP-eEg1hOOu66-6rJKfmpA70A)
> > > > 
> > > > 
> > > > 好的，其实官方很多东西我都没写，最后就加个tls吧
> > > 
> > > 
> > > 感谢
> > 
> > 
> > 我 Push 了个新版本，但是我没有 TLS 环境测试，要不你试试用下？ https://github.com/GenshinMinecraft/nezha-agent-rs/actions/runs/10756674232
> 
> 测了一下，可以正常使用了，感谢
> 
> 不过这个内存的读数是不是有问题？是把buff/cache也算在使用内存中了吗？ ![图片](https://private-user-images.githubusercontent.com/128272411/365412479-34ca16e3-3b4a-488e-896f-5c557f7b0b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjY4NzUsIm5iZiI6MTcyNTc2NjU3NSwicGF0aCI6Ii8xMjgyNzI0MTEvMzY1NDEyNDc5LTM0Y2ExNmUzLTNiNGEtNDg4ZS04OTZmLTVjNTU3ZjdiMGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMzM2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGJlMjgyYWQ4ZWMxZTJlNmI1YjY5NGM3ZTBjZGE4MDcwOWIzY2IxZmE0OTAyMTkwYzUxM2MyNWZjYjEyZjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.od2eHAJSdl1GEcmIN8FBNl58oXqixGDjcN3UvEklwfI)

算是吧，我用的库没有分那么细的，所以可能会偏高了点
